workflows:
  ios:
    name: Build iOS app
    max_build_duration: 60
    scripts:
      - name: Install dependencies
        script: |
          npm install  # Installiert die Abhängigkeiten deines Projekts
          cd ios && pod install  # Installiert CocoaPods für iOS
      - name: Build iOS app
        script: |
          xcodebuild -workspace ios/YourApp.xcworkspace -scheme YourApp -sdk iphoneos
