workflows:
  ios:
    name: Build iOS app
    max_build_duration: 60
    platform: ios  # Hier steht 'platform', keine weiteren Felder wie 'ios' sind erlaubt
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build iOS app
        script: |
          expo build:ios --no-wait
