workflows:
  ios:
    name: Build iOS app
    max_build_duration: 60
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build iOS app
        script: |
          expo build:ios --no-wait
