version: 1.0

workflows:
  ios:
    name: Build iOS
    # Keine "platform"-Angabe erforderlich für Codemagic
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
          expo install
      - name: Build iOS app
        script: |
          expo build:ios
